### ISSUE TITLE
Replication config management

### ISSUE THREAD

**Issue by ad-bitmed** [scality/cloudserver#1512]
I'm trying to move all data replication to AWS S3 as opposed to having all data replicated locally on the CloudServer machine. 

Scenario:
1. Configure an AWS S3 backend:
$ cat locationConfig.json 
{
    "us-east-1": {
        "type": "file",
        "objectId": "us-east-1",
        "legacyAwsBehavior": true,
        "details": {}
    },
    "us":  {
    	"type": "aws_s3",
    	"objectId": "us-1",
	"legacyAwsBehavior": true,
    	"details": {
        	"awsEndpoint": "s3.amazonaws.com",
        	"bucketName": "app-store",
       		"bucketMatch": false,
        	"credentials": {
            		"accessKey": "<AWS_ACCESS_KEY>",
            		"secretKey": "<AWS_SECRET_KEY>"
        	}
    	}
    }
}

2. Delete all replication endpoints:
$ cat config.json
{
    "port": 8000,
    "listenOn": [],
    "replicationGroupId": "",
    "restEndpoints": {
	"data.mydomain.com": "us"
    },
    "websiteEndpoints": [],
    "replicationEndpoints": [],
    "backbeat": {
        "host": "localhost",
        "port": 8900
    },
    "cdmi": {
        "host": "localhost",
        "port": 81,
        "path": "/dewpoint",
        "readonly": true
    },
    "bucketd": {
        "bootstrap": ["localhost"]
    },
    "vaultd": {
        "host": "localhost",
        "port": 8500
    },
    "clusters": 1,
    "log": {
        "logLevel": "info",
        "dumpLevel": "error"
    },
    "healthChecks": {
        "allowFrom": ["127.0.0.1/8", "::1"]
    },
    "metadataClient": {
        "host": "localhost",
        "port": 9990
    },
    "dataClient": {
        "host": "localhost",
        "port": 9991
    },
    "metadataDaemon": {
        "bindAddress": "localhost",
        "port": 9990
    },
    "dataDaemon": {
        "bindAddress": "localhost",
        "port": 9991
    },
    "recordLog": {
        "enabled": true,
        "recordLogName": "s3-recordlog"
    },
    "mongodb": {
       "replicaSetHosts": "localhost:27018,localhost:27019,localhost:27020",
       "writeConcern": "majority",
       "replicaSet": "rs0",
       "readPreference": "primary",
       "database": "metadata"
    }
}

3. Create bucket located in AWS S3:
$ aws s3api create-bucket --bucket test1000 --create-bucket-configuration LocationConstraint=us --endpoint http://data.mydomain.com:8000
$ aws s3 --endpoint http://data.mydomain.com:8000 ls
2018-08-28 22:07:36 test1000

4. Upload a file:
$ aws s3 --endpoint http://data.mydomain.com:8000 cp file_10MB.bin s3://test1000
upload: ./file_10MB.bin to s3://test1000/file_10MB.bin
$ aws s3 --endpoint http://data.mydomain.com:8000 ls s3://test1000
2018-08-29 08:42:02   10485760 file_10MB.bin

5. Delete the file using the AWS S3 console: https://s3.console.aws.amazon.com/

6. Look up the file using CloudServer API:
$ aws s3 --endpoint http://data.mydomain.com:8000 ls s3://test1000
2018-08-29 08:42:02   10485760 file_10MB.bin
NOTE that the file is no longer present in Amazon S3. 

7. Download the file using the CloudServer API:
$ aws s3 --endpoint http://data.mydomain.com:8000 cp s3://test1000/file_10MB.bin tmp/
(download successful)

The question is: how can I turn off local replication and use only the 3rd party backend?

Thanks in advance!

**Comment by smaffulli** [comment]
@ad-bitmed I'm not sure I understand the question... Could you please explain your use case a bit more?

**Comment by dora-korpar** [comment]
Hi @ad-bitmed, 

If I understand correctly, you don't want CloudServer to be able to access the data you put to AWS.
If that's the case, it's actually not an issue with your replication configuration.
The behavior you're seeing is due to versioning being enabled on your AWS bucket. Because it's enabled, when you delete the file on the AWS console, it's actually creating a new version with a Delete Marker. Since that action did not go through CloudServer, the version id CloudServer has saved in metadata is the id of the originally put object. When you then get that object through CloudServer, it's using the original version id, and so getting the non-current version that still exists on AWS.

If you'd like the object to be inaccessible through CloudServer, just include the version id when you delete the object from AWS. You just might want to be sure your data is replicated the way you want before deleting the version!

**Comment by smaffulli** [comment]
Let's close this question and move the conversation to https://forum.zenko.io/, in case @ad-bitmed or others need more explanations.
